common: &common
  adapter:  postgresql
  host: localhost
  username: showbomber
  password: sh0wb0mb3r
  pool: 5
  timeout: 5000

development:
  <<: *common
  database: showbomber_dev

test:
  <<: *common
  database: showbomber_test
  min_messages: WARNING

production:
  <<: *common
  database: showbomber_production
